# Generated by Django 4.2.5 on 2023-09-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsetimate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curr_inv',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
