# Generated by Django 4.2.5 on 2023-09-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsetimate', '0002_alter_user_curr_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
