# Generated by Django 4.2.5 on 2023-09-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invsetimate', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
