# Generated by Django 4.2.5 on 2023-09-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsetimate', '0005_alter_watchlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='holdings',
            field=models.IntegerField(default=0),
        ),
    ]
