# Generated by Django 4.2.5 on 2023-09-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsetimate', '0006_portfolio_holdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='type',
            field=models.CharField(default='', max_length=5),
        ),
    ]
