# Generated by Django 4.2.5 on 2023-09-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invsetimate', '0007_portfolio_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='type',
        ),
    ]
